### ISSUE TITLE
Release 0.1.0 misses Windows binaries

### ISSUE THREAD

**Issue by koppor** [NiclasvanEyk/keepac#22]
https://github.com/NiclasvanEyk/keepac/releases/tag/0.1.0 does not contain any `.exe` (as promised in the README.md). Version 0.0.9 did: https://github.com/NiclasvanEyk/keepac/releases/tag/0.0.9

**Comment by NiclasvanEyk** [comment]
I can see three entries for Windows builds at the bottom of the archive list in the release:

<img width="1392" alt="Screenshot 2024-03-15 at 18 04 42" src="https://github.com/NiclasvanEyk/keepac/assets/10284694/d09c9461-f638-4ac3-aff1-78ba0392f89b">

E.g. here is the link to the x86-64 version: https://github.com/NiclasvanEyk/keepac/releases/download/0.1.0/keepac_Windows_x86_64.zip
Downloaded and unzipped the archive and it contains a `keepac.exe`
